### ISSUE TITLE
Getting Unknown encoding: { 'Content-Type': 'image/png' }

### ISSUE THREAD

**Issue by anuragvohraec** [asd20752/node-mbtiles#1]
Hi Adrian,

I tried running this code , which gives me this error:
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: { 'Content-Type': 'image/png' }
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:293:13)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at ServerResponse._writeRaw (node:_http_outgoing:363:17)
    at ServerResponse._send (node:_http_outgoing:339:15)
    at write_ (node:_http_outgoing:785:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at Statement.<anonymous> (/home/anurag/Documents/projects/project_yelo/geo/node-mbtiles/node-mbtiles/main.js:72:21) {
  code: 'ERR_UNKNOWN_ENCODING'
}
```

Steps followed to reproduce this:
1. Went to BBBike to extract MBT files for a limited location
![image](https://user-images.githubusercontent.com/53807480/178908603-6d766d4d-bb3b-4ce1-a5f8-1ae9cb558649.png)

MBT file I used:
Just rename this files : by removing zip from file name extension
[ashta.mbtiles.zip](https://github.com/asd20752/node-mbtiles/files/9108845/ashta.mbtiles.zip)

2. Placed it in root folder of the  `node-mbtiles`, and did `npm install`
3. Ran the code by : `node main.js -p 3030`
I modified the code a little:
```js
const databases = {
    ashta: {
        filePath: "ashta.mbtiles"
    }
};
```
4. When I go to url `http://localhost:3030/ashta/0/0/0` I get the error.

Please assist how do we solev this issue.

**Comment by asd20752** [comment]
The reason behind this is since this script is made for raster and not vector tiles. Should not be much in the need of change so will se if I can get the time to update the script in the near future. 
In the mean time without testing or having looked at the code for a while changing "image/png" to "application/octet-stream" could solve the problem.

**Comment by anuragvohraec** [comment]
ok thank you, made it working. Thanx for your help.
